#!/bin/bash
make

function test()
{
    LD_PRELOAD=./libmy_malloc.so $1 > /dev/null
    if [[ $? == 0 ]]; then
       echo -e "Test: [\e[1;95m$1\e[0m] == \e[1;32mOK\e[0m"
    else
        echo -e "Test: [\e[1;95m$1\e[0m] == \e[1;91;5mKO\e[0m"
    fi
}

test "ls"
test "tree"
test "ls -R"
test "ls -a"
test "ls -l"
test "ls -lR"
test "cat Makefile"
